# Generated by Django 5.2.8 on 2025-11-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_category_monitor_food_category_category_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='menu.monitor'),
        ),
    ]
